### PR TITLE
Add Template-level edit support & Use CDN to save S3 cost

### PR DESCRIPTION
**Pull request by sdh21**
## Template-level edit support

(1) Abstract renderer out of adapter
     Data Flow: resume.js -> resume_adapter.js -> resume_render.js
(2) Override Helper (override_helper.rb)
     Executes resume_adapter.js to get all template fields.

Override Helper has two interfaces:
```ruby
  # Get template fields
  hmap = get_template_fields("./template_0/js/resume.js", "./template_0")
  # Change website-title
  hmap["website-title"] = "changed"
  override_info = get_override_info_from_hashmap(hmap)
```
And the bundle helper needs override_info as part of the parameters.

 @Tracylmt
 
-----------------------------

Still working on getting all the fields directly without a resume.
The interface is supposed to be:
```ruby
hmap = get_template_fields("", "./template_0")
 ```

-----------------------------

And it is up to you what "./template_0/js/resume.js" is. I don't understand the use cases very clearly. @ me if you need the path to be a URL.

 ## Use CDN to save S3 cost

 Delete all js/css libraries. Use CDN instead.

### CODE REVIEW

**Review by Tracylmt — APPROVED** [review]

**Comment by JunqiZhang0** [comment]
app/helpers/functions/web_resume/deploy_helper.rb is empty file?

**Review by JunqiZhang0 — CHANGES_REQUESTED** [review]
please squash the commits into one and remove empty file, rest part look good to me

**Comment by sdh21** [comment]
> app/helpers/functions/web_resume/deploy_helper.rb is empty file?

No.

https://github.com/ESaaS-4995/WebZero/blob/dev-edit-support/app/helpers/functions/web_resume/deploy_helper.rb

**Comment by sdh21** [comment]
> please squash the commits into one and remove empty file, rest part look good to me

I think github can squash. Click the arrow right to the "Merge pull request" button maybe?

**Review by JunqiZhang0 — APPROVED** [review]
LGTM

**Review by CynGao — APPROVED** [review]

**Pull request merged**
